[application]
name = "PrsnlAssistant"
default_platform = "desktop"

# Asset configuration
[application.asset_dir]
path = "assets"

[web.app]
title = "Personal Assistant"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = []
script = []

[bundle.identifier]
# Android bundle identifier
android = "com.prsnl.assistant"

# iOS bundle identifier (for future)
ios = "com.prsnl.assistant"
