[application]
name = "PrsnlAssistant"
default_platform = "desktop"
asset_dir = "assets"

[web.app]
title = "PrsnlAssistant"

[web.watcher]
reload_html = true
watch_path = ["crates", "apps", "assets"]

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []

[bundle]
identifier = "com.prsnl.assistant"
